export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS-REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCES";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"; 

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCTS-REQUEST";
export const GET_PRODUCT_DETAILES_SUCCESS = "GET_PRODUCTS_SUCCES";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCTS_FAIL"; 